DROP DATABASE IF EXISTS search;
-- DROP USER IF EXISTS search_user;

CREATE USER search_user IDENTIFIED BY 'dbuser123';
CREATE DATABASE search CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON search.* TO search_user WITH GRANT OPTION;

USE search;

CREATE TABLE topic(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NULL DEFAULT NULL,
    description VARCHAR(5000) NULL DEFAULT NULL,
    text_field1 VARCHAR(5000) NULL DEFAULT NULL,
    text_field2 VARCHAR(5000) NULL DEFAULT NULL,
    created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;